import {
  calculateFinalRemainingLife,
  estimateCurrentMileage,
  getMaintenanceStatus,
  type MileageReadingInput,
} from "@/lib/maintenance-engine";

export const asOfDate = new Date("2026-07-27T12:00:00-04:00");

export const demoShop = {
  id: "shop-demo",
  name: "Cedar Bay Auto Works",
  slug: "cedar-bay-auto",
  timezone: "America/New_York",
  dailyBayHours: 64,
};

export const demoUsers = [
  {
    id: "user-owner",
    shopId: demoShop.id,
    name: "Avery Stone",
    email: "owner@maintiva.dev",
    role: "OWNER",
  },
  {
    id: "user-advisor",
    shopId: demoShop.id,
    name: "Maya Torres",
    email: "advisor@maintiva.dev",
    role: "SERVICE_ADVISOR",
  },
];

export const customers = [
  {
    id: "cust-justin",
    shopId: demoShop.id,
    firstName: "Justin",
    lastName: "Camacho",
    phone: "(404) 555-0187",
    email: "justin@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 94,
    lifetimeRevenueCents: 642500,
    lastVisit: "2026-05-09",
    notes: "Prefers morning appointments and consolidated work.",
  },
  {
    id: "cust-john",
    shopId: demoShop.id,
    firstName: "John",
    lastName: "Doe",
    phone: "(404) 555-0142",
    email: "john.doe@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: true,
    callConsent: false,
    status: "WATCHLIST",
    customerScore: 88,
    lifetimeRevenueCents: 391500,
    lastVisit: "2026-02-18",
    notes: "No response to last brake-fluid recommendation.",
  },
  {
    id: "cust-priya",
    shopId: demoShop.id,
    firstName: "Priya",
    lastName: "Nair",
    phone: "(404) 555-0124",
    email: "priya@example.com",
    preferredContact: "EMAIL",
    smsConsent: false,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 79,
    lifetimeRevenueCents: 214900,
    lastVisit: "2026-06-03",
    notes: "Fleet-lite family account with two vehicles.",
  },
  {
    id: "cust-marcus",
    shopId: demoShop.id,
    firstName: "Marcus",
    lastName: "Bell",
    phone: "(404) 555-0181",
    email: "marcus@example.com",
    preferredContact: "CALL",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 73,
    lifetimeRevenueCents: 182000,
    lastVisit: "2025-12-12",
    notes: "High-mileage commuter.",
  },
  {
    id: "cust-elena",
    shopId: demoShop.id,
    firstName: "Elena",
    lastName: "Park",
    phone: "(404) 555-0162",
    email: "elena@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: false,
    callConsent: false,
    status: "ACTIVE",
    customerScore: 69,
    lifetimeRevenueCents: 98000,
    lastVisit: "2026-01-21",
    notes: "Newer customer. Needs trust-building reminders.",
  },
  {
    id: "cust-sam",
    shopId: demoShop.id,
    firstName: "Sam",
    lastName: "Rivera",
    phone: "(404) 555-0109",
    email: "sam@example.com",
    preferredContact: "EMAIL",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 83,
    lifetimeRevenueCents: 456000,
    lastVisit: "2026-04-15",
    notes: "Usually approves bundled preventative work.",
  },
  {
    id: "cust-lydia",
    shopId: demoShop.id,
    firstName: "Lydia",
    lastName: "Morgan",
    phone: "(404) 555-0156",
    email: "lydia@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 61,
    lifetimeRevenueCents: 87500,
    lastVisit: "2026-07-01",
    notes: "Recently completed inspection.",
  },
  {
    id: "cust-noah",
    shopId: demoShop.id,
    firstName: "Noah",
    lastName: "Kim",
    phone: "(404) 555-0173",
    email: "noah@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: true,
    callConsent: false,
    status: "ACTIVE",
    customerScore: 77,
    lifetimeRevenueCents: 264000,
    lastVisit: "2026-03-30",
    notes: "Asks for clear price estimates before booking.",
  },
  {
    id: "cust-amara",
    shopId: demoShop.id,
    firstName: "Amara",
    lastName: "Lewis",
    phone: "(404) 555-0133",
    email: "amara@example.com",
    preferredContact: "EMAIL",
    smsConsent: false,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 81,
    lifetimeRevenueCents: 301000,
    lastVisit: "2026-05-27",
    notes: "Warranty-sensitive.",
  },
  {
    id: "cust-owen",
    shopId: demoShop.id,
    firstName: "Owen",
    lastName: "Reed",
    phone: "(404) 555-0198",
    email: "owen@example.com",
    preferredContact: "CALL",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 72,
    lifetimeRevenueCents: 176500,
    lastVisit: "2026-06-19",
    notes: "Needs tire replacement education.",
  },
  {
    id: "cust-nina",
    shopId: demoShop.id,
    firstName: "Nina",
    lastName: "Patel",
    phone: "(404) 555-0104",
    email: "nina@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "PAUSED",
    customerScore: 58,
    lifetimeRevenueCents: 73500,
    lastVisit: "2025-09-16",
    notes: "Automation paused by advisor until September.",
  },
  {
    id: "cust-ethan",
    shopId: demoShop.id,
    firstName: "Ethan",
    lastName: "Brooks",
    phone: "(404) 555-0191",
    email: "ethan@example.com",
    preferredContact: "EMAIL",
    smsConsent: true,
    emailConsent: true,
    callConsent: false,
    status: "ACTIVE",
    customerScore: 86,
    lifetimeRevenueCents: 337000,
    lastVisit: "2026-02-05",
    notes: "Good candidate for bundled scheduling.",
  },
  {
    id: "cust-carmen",
    shopId: demoShop.id,
    firstName: "Carmen",
    lastName: "Soto",
    phone: "(404) 555-0112",
    email: "carmen@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 67,
    lifetimeRevenueCents: 129900,
    lastVisit: "2026-04-02",
    notes: "Prefers text confirmations.",
  },
  {
    id: "cust-victor",
    shopId: demoShop.id,
    firstName: "Victor",
    lastName: "Chen",
    phone: "(404) 555-0167",
    email: "victor@example.com",
    preferredContact: "EMAIL",
    smsConsent: true,
    emailConsent: true,
    callConsent: true,
    status: "ACTIVE",
    customerScore: 91,
    lifetimeRevenueCents: 502500,
    lastVisit: "2026-06-24",
    notes: "Approves proactive work when bundled well.",
  },
  {
    id: "cust-zoe",
    shopId: demoShop.id,
    firstName: "Zoe",
    lastName: "Harris",
    phone: "(404) 555-0144",
    email: "zoe@example.com",
    preferredContact: "SMS",
    smsConsent: true,
    emailConsent: false,
    callConsent: false,
    status: "ACTIVE",
    customerScore: 74,
    lifetimeRevenueCents: 228000,
    lastVisit: "2026-01-09",
    notes: "College commuter.",
  },
];

export const vehicles = [
  {
    id: "veh-jeep",
    shopId: demoShop.id,
    customerId: "cust-justin",
    year: 2003,
    make: "Jeep",
    model: "Wrangler",
    vin: "1J4FA49S03P123456",
    engine: "4.0L I6",
    trim: "Sport",
    currentMileage: 98600,
    estimatedAnnualMileage: 12000,
    overallHealth: 72,
    lastServiceDate: "2026-05-09",
  },
  {
    id: "veh-accord",
    shopId: demoShop.id,
    customerId: "cust-john",
    year: 2019,
    make: "Honda",
    model: "Accord",
    vin: "1HGCV1F37KA100001",
    engine: "1.5L Turbo",
    trim: "EX",
    currentMileage: 64250,
    estimatedAnnualMileage: 15500,
    overallHealth: 58,
    lastServiceDate: "2026-02-18",
  },
  {
    id: "veh-rav4",
    shopId: demoShop.id,
    customerId: "cust-priya",
    year: 2021,
    make: "Toyota",
    model: "RAV4",
    vin: "2T3P1RFV8MW100002",
    engine: "2.5L",
    trim: "XLE",
    currentMileage: 38400,
    estimatedAnnualMileage: 11200,
    overallHealth: 86,
    lastServiceDate: "2026-06-03",
  },
  {
    id: "veh-f150",
    shopId: demoShop.id,
    customerId: "cust-priya",
    year: 2016,
    make: "Ford",
    model: "F-150",
    vin: "1FTEW1EP3GFA00003",
    engine: "2.7L EcoBoost",
    trim: "XLT",
    currentMileage: 112300,
    estimatedAnnualMileage: 9000,
    overallHealth: 64,
    lastServiceDate: "2026-03-14",
  },
  {
    id: "veh-silverado",
    shopId: demoShop.id,
    customerId: "cust-marcus",
    year: 2015,
    make: "Chevrolet",
    model: "Silverado",
    vin: "3GCUKREC4FG100004",
    engine: "5.3L V8",
    trim: "LT",
    currentMileage: 149800,
    estimatedAnnualMileage: 19000,
    overallHealth: 49,
    lastServiceDate: "2025-12-12",
  },
  {
    id: "veh-outback",
    shopId: demoShop.id,
    customerId: "cust-elena",
    year: 2018,
    make: "Subaru",
    model: "Outback",
    vin: "4S4BSANC8J3100005",
    engine: "2.5L",
    trim: "Limited",
    currentMileage: 76200,
    estimatedAnnualMileage: 13400,
    overallHealth: 55,
    lastServiceDate: "2026-01-21",
  },
  {
    id: "veh-camry",
    shopId: demoShop.id,
    customerId: "cust-sam",
    year: 2020,
    make: "Toyota",
    model: "Camry",
    vin: "4T1G11AK0LU100006",
    engine: "2.5L",
    trim: "SE",
    currentMileage: 58900,
    estimatedAnnualMileage: 14200,
    overallHealth: 78,
    lastServiceDate: "2026-04-15",
  },
  {
    id: "veh-civic",
    shopId: demoShop.id,
    customerId: "cust-lydia",
    year: 2022,
    make: "Honda",
    model: "Civic",
    vin: "2HGFE2F56NH100007",
    engine: "2.0L",
    trim: "Sport",
    currentMileage: 24100,
    estimatedAnnualMileage: 11800,
    overallHealth: 92,
    lastServiceDate: "2026-07-01",
  },
  {
    id: "veh-telluride",
    shopId: demoShop.id,
    customerId: "cust-victor",
    year: 2021,
    make: "Kia",
    model: "Telluride",
    vin: "5XYP3DHC5MG100008",
    engine: "3.8L V6",
    trim: "EX",
    currentMileage: 49750,
    estimatedAnnualMileage: 12800,
    overallHealth: 81,
    lastServiceDate: "2026-06-24",
  },
];

export const serviceDefinitions = [
  ["Oil Change", "Fluids", 5000, 6, 10, 30, 8500],
  ["Tire Rotation", "Tires", 7500, 6, 10, 30, 4500],
  ["Brake Pads", "Brakes", 40000, 36, 20, 90, 36000],
  ["Brake Rotors", "Brakes", 70000, 60, 15, 120, 52000],
  ["Brake Fluid", "Fluids", 30000, 24, 20, 45, 15000],
  ["Transmission Fluid", "Drivetrain", 60000, 60, 15, 90, 26000],
  ["Coolant", "Fluids", 50000, 48, 15, 60, 18000],
  ["Differential Fluid", "Drivetrain", 50000, 48, 15, 60, 19000],
  ["Spark Plugs", "Ignition", 90000, 84, 15, 120, 34000],
  ["Engine Air Filter", "Filters", 15000, 12, 10, 15, 4200],
  ["Cabin Air Filter", "Filters", 15000, 12, 10, 15, 3800],
  ["Timing Belt", "Engine", 100000, 84, 15, 240, 95000],
  ["Serpentine Belt", "Engine", 60000, 48, 15, 45, 14500],
  ["Battery", "Electrical", 50000, 48, 10, 30, 22000],
  ["Wiper Blades", "Safety", 12000, 12, 10, 10, 3200],
  ["Tires", "Tires", 50000, 60, 20, 90, 82000],
].map(
  ([
    name,
    category,
    defaultMileageInterval,
    defaultTimeIntervalMonths,
    defaultNotificationThreshold,
    estimatedLaborMinutes,
    defaultPriceCents,
  ]) => ({
    id: `svc-${String(name).toLowerCase().replaceAll(" ", "-")}`,
    shopId: demoShop.id,
    name: String(name),
    category: String(category),
    defaultMileageInterval: Number(defaultMileageInterval),
    defaultTimeIntervalMonths: Number(defaultTimeIntervalMonths),
    defaultNotificationThreshold: Number(defaultNotificationThreshold),
    estimatedLaborMinutes: Number(estimatedLaborMinutes),
    defaultPriceCents: Number(defaultPriceCents),
    description: `Default ${name} lifecycle configured for ${demoShop.name}.`,
    isActive: true,
  }),
);

export const mileageReadings: Record<string, MileageReadingInput[]> = {
  "veh-jeep": [
    {
      mileage: 92000,
      recordedAt: "2026-01-10",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
    {
      mileage: 96800,
      recordedAt: "2026-05-09",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
  "veh-accord": [
    {
      mileage: 56600,
      recordedAt: "2025-10-18",
      source: "IMPORTED",
      confidence: "IMPORTED",
    },
    {
      mileage: 62100,
      recordedAt: "2026-02-18",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
  "veh-rav4": [
    {
      mileage: 35400,
      recordedAt: "2026-02-08",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
    {
      mileage: 37800,
      recordedAt: "2026-06-03",
      source: "CUSTOMER_SMS",
      confidence: "CUSTOMER_CONFIRMED",
    },
  ],
  "veh-f150": [
    {
      mileage: 107900,
      recordedAt: "2025-10-14",
      source: "IMPORTED",
      confidence: "IMPORTED",
    },
    {
      mileage: 111200,
      recordedAt: "2026-03-14",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
  "veh-silverado": [
    {
      mileage: 137400,
      recordedAt: "2025-04-08",
      source: "IMPORTED",
      confidence: "IMPORTED",
    },
    {
      mileage: 145900,
      recordedAt: "2025-12-12",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
  "veh-outback": [
    {
      mileage: 69600,
      recordedAt: "2025-07-21",
      source: "IMPORTED",
      confidence: "IMPORTED",
    },
    {
      mileage: 73850,
      recordedAt: "2026-01-21",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
  "veh-camry": [
    {
      mileage: 52300,
      recordedAt: "2025-10-15",
      source: "IMPORTED",
      confidence: "IMPORTED",
    },
    {
      mileage: 56100,
      recordedAt: "2026-04-15",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
  "veh-civic": [
    {
      mileage: 21900,
      recordedAt: "2026-02-01",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
    {
      mileage: 23800,
      recordedAt: "2026-07-01",
      source: "CUSTOMER_PORTAL",
      confidence: "CUSTOMER_CONFIRMED",
    },
  ],
  "veh-telluride": [
    {
      mileage: 44500,
      recordedAt: "2025-11-24",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
    {
      mileage: 48600,
      recordedAt: "2026-06-24",
      source: "SHOP_REPAIR_ORDER",
      confidence: "VERIFIED",
    },
  ],
};

const itemSeeds = [
  ["veh-jeep", "Oil Change", "2026-05-09", 96800, 12, null],
  ["veh-jeep", "Brake Pads", "2025-11-12", 90200, 34, 25],
  ["veh-jeep", "Cabin Air Filter", "2025-07-10", 84200, 10, null],
  ["veh-jeep", "Differential Fluid", "2022-08-10", 61200, 20, null],
  ["veh-accord", "Oil Change", "2026-02-18", 62100, 10, null],
  ["veh-accord", "Brake Fluid", "2024-03-12", 38200, 20, null],
  ["veh-accord", "Cabin Air Filter", "2025-02-18", 48100, 10, null],
  ["veh-rav4", "Oil Change", "2026-06-03", 37800, 10, null],
  ["veh-f150", "Transmission Fluid", "2021-04-04", 68900, 15, null],
  ["veh-silverado", "Spark Plugs", "2020-03-16", 58800, 15, 8],
  ["veh-outback", "Brake Pads", "2024-07-21", 51200, 20, 17],
  ["veh-camry", "Tire Rotation", "2026-04-15", 56100, 10, null],
  ["veh-civic", "Oil Change", "2026-07-01", 23800, 10, null],
  ["veh-telluride", "Battery", "2022-06-24", 18200, 10, 18],
  ["veh-telluride", "Coolant", "2023-06-24", 24700, 15, null],
];

export const maintenanceItems = itemSeeds.map(
  ([
    vehicleId,
    serviceName,
    lastCompletedDate,
    lastCompletedMileage,
    notificationThreshold,
    mechanicRemainingPercentage,
  ]) => {
    const definition = serviceDefinitions.find(
      (service) => service.name === serviceName,
    );
    const vehicle = vehicles.find((item) => item.id === vehicleId);
    const mileage = estimateCurrentMileage(
      mileageReadings[String(vehicleId)] ?? [],
      asOfDate,
    );
    const calculation = calculateFinalRemainingLife({
      lastCompletedDate: String(lastCompletedDate),
      lastCompletedMileage: Number(lastCompletedMileage),
      recommendedMileageInterval: definition?.defaultMileageInterval ?? 5000,
      recommendedTimeIntervalMonths:
        definition?.defaultTimeIntervalMonths ?? 6,
      notificationThreshold: Number(notificationThreshold),
      estimatedCurrentMileage: mileage.mileage,
      mechanicRemainingPercentage:
        mechanicRemainingPercentage === null
          ? null
          : Number(mechanicRemainingPercentage),
      asOf: asOfDate,
    });

    return {
      id: `item-${vehicleId}-${String(serviceName).toLowerCase().replaceAll(" ", "-")}`,
      shopId: demoShop.id,
      vehicleId: String(vehicleId),
      customerId: vehicle?.customerId ?? "",
      serviceDefinitionId: definition?.id ?? "",
      serviceName: String(serviceName),
      lastCompletedDate: String(lastCompletedDate),
      lastCompletedMileage: Number(lastCompletedMileage),
      recommendedMileageInterval: definition?.defaultMileageInterval ?? 5000,
      recommendedTimeIntervalMonths: definition?.defaultTimeIntervalMonths ?? 6,
      remainingMileage:
        Number(lastCompletedMileage) +
        (definition?.defaultMileageInterval ?? 5000) -
        mileage.mileage,
      notificationThreshold: Number(notificationThreshold),
      estimatedLaborMinutes: definition?.estimatedLaborMinutes ?? 30,
      estimatedPriceCents: definition?.defaultPriceCents ?? 10000,
      mechanicRemainingPercentage:
        mechanicRemainingPercentage === null
          ? null
          : Number(mechanicRemainingPercentage),
      ...calculation,
      status: getMaintenanceStatus(
        calculation.finalLife,
        Number(notificationThreshold),
      ),
    };
  },
);

export const communications = [
  {
    id: "comm-1",
    customerId: "cust-john",
    vehicleId: "veh-accord",
    channel: "SMS",
    template: "MAINTENANCE_DUE_SOON",
    sentAt: "2026-07-05",
    deliveryStatus: "SIMULATED",
    responseStatus: "NO_RESPONSE",
  },
  {
    id: "comm-2",
    customerId: "cust-justin",
    vehicleId: "veh-jeep",
    channel: "EMAIL",
    template: "MILEAGE_CONFIRMATION",
    sentAt: "2026-07-11",
    deliveryStatus: "SIMULATED",
    responseStatus: "REPLIED",
  },
  {
    id: "comm-3",
    customerId: "cust-victor",
    vehicleId: "veh-telluride",
    channel: "SMS",
    template: "APPOINTMENT_CONFIRMATION",
    sentAt: "2026-07-22",
    deliveryStatus: "SIMULATED",
    responseStatus: "BOOKED",
  },
];

export const appointments = [
  {
    id: "appt-1",
    customerId: "cust-justin",
    vehicleId: "veh-jeep",
    scheduledStart: "2026-07-27T09:00:00-04:00",
    scheduledEnd: "2026-07-27T12:00:00-04:00",
    status: "CONFIRMED",
    services: ["Oil Change", "Brake Pads", "Cabin Air Filter", "Differential Fluid"],
    estimatedLaborMinutes: 180,
    estimatedRevenueCents: 68200,
    source: "AUTOMATION",
  },
  {
    id: "appt-2",
    customerId: "cust-victor",
    vehicleId: "veh-telluride",
    scheduledStart: "2026-07-28T13:30:00-04:00",
    scheduledEnd: "2026-07-28T15:30:00-04:00",
    status: "CONFIRMED",
    services: ["Battery", "Coolant"],
    estimatedLaborMinutes: 120,
    estimatedRevenueCents: 40000,
    source: "CUSTOMER_BOOKING",
  },
];

export const revenueForecast = [
  { label: "Next 7 days", predicted: 184500, scheduled: 108200 },
  { label: "Next 30 days", predicted: 841000, scheduled: 315500 },
  { label: "Next 60 days", predicted: 1462000, scheduled: 502000 },
  { label: "Next 90 days", predicted: 2185000, scheduled: 706000 },
];

export const customerLookup = Object.fromEntries(
  customers.map((customer) => [
    customer.id,
    {
      name: `${customer.firstName} ${customer.lastName}`,
      firstName: customer.firstName,
      preferredContact: customer.preferredContact,
    },
  ]),
);

export const vehicleLookup = Object.fromEntries(
  vehicles.map((vehicle) => [
    vehicle.id,
    {
      label: `${vehicle.year} ${vehicle.make} ${vehicle.model}`,
      ...vehicle,
    },
  ]),
);

export function getCustomer(customerId: string) {
  return customers.find((customer) => customer.id === customerId);
}

export function getVehicle(vehicleId: string) {
  return vehicles.find((vehicle) => vehicle.id === vehicleId);
}

export function getCustomerVehicles(customerId: string) {
  return vehicles.filter((vehicle) => vehicle.customerId === customerId);
}

export function getVehicleMaintenance(vehicleId: string) {
  return maintenanceItems.filter((item) => item.vehicleId === vehicleId);
}
